/* Verilog module instantiation template generated by SCUBA Diamond_2.0_Production (151) */
/* Module Version: 7.1 */
/* Wed Mar 13 03:10:07 2013 */

/* parameterized module instance */
ram_dp_true __ (.DataInA( ), .DataInB( ), .AddressA( ), .AddressB( ), 
    .ClockA( ), .ClockB( ), .ClockEnA( ), .ClockEnB( ), .WrA( ), .WrB( ), 
    .ResetA( ), .ResetB( ), .QA( ), .QB( ));
